name: hackage

on:
  push:
    paths:
      - ".github/workflows/hackage.yml"
  release:
    types:
      - released
      - prereleased

jobs:
  publish-to-hackage:
    name: "Publish to Hackage"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        id: install-haskell
        with:
          stack-no-global: true
          enable-stack: true
          stack-version: "latest"

      - name: Configure stack
        run: |
          mkdir -p ${{ steps.install-haskell.outputs.stack-root }}
          echo "save-hackage-creds: false" >> ${{ steps.install-haskell.outputs.stack-root }}/config.yaml

      - name: Publish `c14n`
        if: startsWith(github.ref, 'refs/tags/c14n-') && github.event.action == 'released'
        run: stack upload . --candidate
        env:
          HACKAGE_USERNAME: ${{ secrets.HACKAGE_USER }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
