name: Haskell

on:
  push:
    paths:
      - ".github/workflows/haskell.yml"
      - "cbits/**"
      - "src/**"
      - "package.yaml"
      - "stack*.yaml"
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        resolver:
          - stack

    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get install libxml2-dev

      - uses: actions/checkout@v4

      - uses: mbg/actions/stack/build@v0.1
        with:
          resolver: ${{ matrix.resolver }}
