name: "Stackage Nightly"

on:
  push:
    paths:
      - ".github/workflows/stackage-nightly.yml"
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get install libxml2-dev

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build with nightly resolver
        uses: mbg/actions/stack/nightly@v0.2
